tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - ec3_custom_types: https://raw.githubusercontent.com/grycap/ec3/tosca/tosca/custom_types.yaml

description: >
  TOSCA template for deploying a Galaxy Server using a local LRMS.

metadata:
  name: Galaxy
  display_name: Deploy a Galaxy portal
  icon: images/galaxy.png
  tag: SW
  tag_color: blue
  parents:
   - single-node-disk.yml

topology_template:

  inputs:

    admin_email:
      type: string
      description: Email of the Galaxy admin user
      default: admin@admin.com
    admin_password:
      type: string
      description: Password of the Galaxy admin user
      default: adminpass

  node_templates:

    galaxy_portal:
      type: tosca.nodes.indigo.GalaxyPortal
      capabilities:
        endpoint:
          properties:
            port: 8080
            protocol: tcp
      properties:
        admin_email: { get_input: admin_email }
        admin_password: { get_input: admin_password }
      requirements:
        - lrms: local_lrms
        - host: simple_node

    # type to describe a Galaxy not using any LRMS but using the local system
    local_lrms:
      type: tosca.nodes.indigo.LRMS.FrontEnd.Local
      requirements:
        - host: simple_node

  outputs:
    galaxy_url:
      value: { concat: [ 'https://', get_attribute: [ simple_node, public_address, 0 ], ':8443/' ] }
